stages:
  - deploy
  - smoke_test
  - dast

deploy:
  stage: deploy
  tags:
    - $ENVIRONMENT
  script:
    - echo "Pulling image for user $DOCKER_LOGIN with tag $IMAGE_TAG"
    - 'docker pull $DOCKER_LOGIN/client_server_app:production-$IMAGE_TAG'
    - IMAGE=$DOCKER_LOGIN/client_server_app:production-$IMAGE_TAG docker compose -f docker-compose.hardened.yml up -d
  rules:
    - if: '$ENVIRONMENT != null'

smoke_test:
  stage: smoke_test
  needs:
    - deploy
  tags:
    - $ENVIRONMENT
  script:
    - 'curl -sf http://localhost:${PORT}/info | grep "\"service\":\"${SERVICE}\"" || exit 1'
  rules:
    - if: '$ENVIRONMENT != null'

dast_zap:
  stage: dast
  needs:
    - smoke_test
  image:
    name: ghcr.io/zaproxy/zaproxy:stable@sha256:47b883dca0d77aeef1dbb9b8ce1f4baddde348ad5852666e553456a9ad936111
    entrypoint: [""]
  tags:
    - docker-runner
  script:
    - mkdir -p /zap/wrk && chmod 777 /zap/wrk
    - zap-api-scan.py -t "http://${STAGING_IP}:${PORT}/openapi.json" -f openapi -J zap_report.json -I
    - cp /zap/wrk/zap_report.json ${CI_PROJECT_DIR}/zap_report.json
  artifacts:
    when: always
    paths:
      - zap_report.json
    expire_in: 30 days
    reports:
      dast: zap_report.json
  rules:
    - if: '$ENVIRONMENT == "staging"'