services:
  app:
    image: ${IMAGE}
    read_only: true
    command: python main.py
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    environment:
      - PORT=${PORT:-8000}
      - AUTHOR=${AUTHOR:-v.laptev}
      - SERVICE=${SERVICE:-currency}
      - PYTHONUNBUFFERED=1
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - secure_net

networks:
  secure_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
