[tool.poetry]
name = "app"
version = "1.0.0"
description = "Currency Service"
authors = ["v.laptev"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.23.0"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
fastapi = "^0.135.1"
defusedxml = "^0.7.1"
ansible = "^13.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "ansible-creator (>=26.4.2,<27.0.0)",
    "molecule (>=26.4.0,<27.0.0)",
    "molecule-docker (==2.0.0)",
    "docker (>=7.1.0,<8.0.0)",
    "testinfra (>=6.0.0,<7.0.0)",
    "molecule-plugins (>=25.8.12,<26.0.0)"
]
