---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: k8s-worker1

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
      remote_tmp: /tmp
  env:
    ANSIBLE_FORCE_COLOR: "1"
  inventory:
    hosts:
      all:
        hosts:
          k8s-worker1:

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
