---
- name: Create kubeadm user
  ansible.builtin.user:
    name: "{{ k8s_user }}"
    state: present
    create_home: true

- name: Create keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add k8s key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/k8s-apt-keyring.asc
    mode: '0644'

- name: Add k8s repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/k8s-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    state: present

- name: Install Kubeadm
  ansible.builtin.apt:
    name: kubeadm
    state: present

- name: Hold Kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold
